### ISSUE TITLE
11. Just Use pure leaflet package. No Nuxt plugin.

### ISSUE THREAD

**Issue by artmarydotir** [mohammadpr91/first-front-boiler-plate#11]
![Screenshot from 2021-01-16 13-36-23](https://user-images.githubusercontent.com/11363931/104809114-280b3700-5800-11eb-8030-0bed14044d8a.png)

**Comment by mohammadpr91** [comment]
I used the original leaflet package to display the map. But when importing it as a plugin, it gives the error of not recognizing this. $ L, which is the main package of this plugin. This error does not exist in the leaflet-nuxt package.
In addition, the mentioned error does not occur in manual import of the main package of the leaflet
